### ISSUE TITLE
[Bug Report]: Optifine and OptiFabric 

### ISSUE THREAD

**Issue by willykool2016** [chronosacaria/MCDungeonsWeapons#198]
### Describe the bug; What happened?

I remember using this mod in another server I own and wanted to add it in another, newer version, since its the best weapon mod in range, but the launcher crashes every time the mod is used with OptiFine or OptiFabric on your fabric and forge versions. This makes me sad because I rather go with than without OptiFine so I am unable to use this mod. [THIS IS CLIENT ISSUE ONLY]

### Expected Behavior

I expected the game to at least start

### Mod Version

mcdw-5.0.7-1.19

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

Custom, Only mods are OptiFine, OptiFabric, MC Dungeons Weaponry

### Additional context

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_759 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_898.<init>(class_898.java:103)
	at net.minecraft.class_310.<init>(class_310.java:577)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 11 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method renderFirstPersonItem(Lnet/minecraft/class_742;FFLnet/minecraft/class_1268;FLnet/minecraft/class_1799;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;ZLnet/minecraft/class_1306;)V in mcdw.mixins.json:client.HeldItemRendererMixin from mod mcdw failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mcdw-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_898.<init>(class_898.java:103)
	at net.minecraft.class_310.<init>(class_310.java:577)

**Comment by chronosacaria** [comment]
So, there are a few things here:
1. MCDW is ONLY for Fabric
2. Optifine is closed source
3. We don't support issues related to Optifine due to the absolutely butchering that it does to Minecraft's code

**Comment by chronosacaria** [comment]
Please use Iris instead
