### ISSUE TITLE
[Bug Report]: Dipping Poison on crossbow crashes game when consuming food or water.

### ISSUE THREAD

**Issue by Aesthir** [chronosacaria/MCDungeonsWeapons#253]
### Describe the bug; What happened?

Dipping Poison III on a crossbow in my off hand gives poisoned arrows when consuming a health potion. This works. However, when consuming a water bottle, or a cooked rabbit, or (I assume) anything else, it crashes my game. Removing the crossbow from my off hand fixes the problem.

### Expected Behavior

Game doesn't crash, item is consumed, and no arrows given.

### Mod Version

8.1.0

### Minecraft Launcher

CurseForge

### Operating System

MacOS

### Modpack

My own construction.

### Additional context

A snippet from my logs:
`[05:02:45] [Server thread/WARN]: Failed to handle packet for /[IP]:51795
net.minecraft.class_148: Ticking player
	at net.minecraft.class_3222.method_14226(class_3222.java:574) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:269) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zmm000$carpet$modifiedRunLoop(MinecraftServer.java:13442) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at net.minecraft.class_1309.handler$dlc000$mcdw$applyDippingPoisonPotionConsumption(class_1309.java:26281) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_6040(class_1309.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.redirect$bbh000$carpet$finishedUsingItem(class_3222.java:6388) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_6040(class_3222.java:1176) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_37119(class_1309.java:3023) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_37119(class_3222.java:1699) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_6076(class_1309.java:3010) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2381) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
	... 10 more
[05:02:45] [Server thread/INFO]: aesthirtruth lost connection: Internal server error
[05:02:45] [Server thread/INFO]: aesthirtruth left the game
[05:03:21] [User Authenticator #3/INFO]: UUID of player aesthirtruth is [UUID]
[05:03:21] [Server thread/INFO]: [Handshake] Sending channel query
[05:03:21] [Netty Server IO #2/INFO]: [Handshake] Receiving client channels
[05:03:21] [Netty Server IO #2/INFO]: [Handshake] Handshake completed successfully
[05:03:21] [Server thread/INFO]: aesthirtruth[/[IP]:51966] logged in with entity id 92057 at (-103.08123090284374, 61.29733824349539, -245.13319548253475)
[05:03:21] [Server thread/INFO]: Sending server config values to client
[05:03:21] [Server thread/INFO]: Syncing config to aesthirtruth ([UUID])
[05:03:21] [Server thread/INFO]: aesthirtruth joined the game
[05:03:21] [Netty Server IO #2/INFO]: Receiving client config
[05:03:23] [Netty Server IO #2/INFO]: [ShulkerBoxTooltip] aesthirtruth: protocol version: 2.0
[05:04:01] [Server thread/WARN]: Failed to handle packet for /[IP]:51966
net.minecraft.class_148: Ticking player
	at net.minecraft.class_3222.method_14226(class_3222.java:574) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:269) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zmm000$carpet$modifiedRunLoop(MinecraftServer.java:13442) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at net.minecraft.class_1309.handler$dlc000$mcdw$applyDippingPoisonPotionConsumption(class_1309.java:26281) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_6040(class_1309.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.redirect$bbh000$carpet$finishedUsingItem(class_3222.java:6388) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_6040(class_3222.java:1176) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_37119(class_1309.java:3023) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_37119(class_3222.java:1699) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_6076(class_1309.java:3010) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2381) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
	... 10 more
[05:04:01] [Server thread/INFO]: aesthirtruth lost connection: Internal server error
[05:04:01] [Server thread/INFO]: aesthirtruth left the game
[05:04:18] [User Authenticator #4/INFO]: UUID of player aesthirtruth is [UUID]
[05:04:18] [Server thread/INFO]: [Handshake] Sending channel query
[05:04:20] [Netty Server IO #3/INFO]: [Handshake] Receiving client channels
[05:04:20] [Netty Server IO #3/INFO]: [Handshake] Handshake completed successfully
[05:04:20] [Server thread/INFO]: aesthirtruth[/[IP]:51970] logged in with entity id 92699 at (-89.00497057418634, 64.0, -258.6251449993732)
[05:04:20] [Server thread/INFO]: Sending server config values to client
[05:04:20] [Server thread/INFO]: Syncing config to aesthirtruth ([UUID])
[05:04:20] [Server thread/INFO]: aesthirtruth joined the game
[05:04:20] [Netty Server IO #3/INFO]: Receiving client config
[05:04:20] [Netty Server IO #3/INFO]: [ShulkerBoxTooltip] aesthirtruth: protocol version: 2.0
[05:09:51] [Server thread/WARN]: Failed to handle packet for /[IP]:51970
net.minecraft.class_148: Ticking player
	at net.minecraft.class_3222.method_14226(class_3222.java:574) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:269) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zmm000$carpet$modifiedRunLoop(MinecraftServer.java:13442) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at net.minecraft.class_1309.handler$dlc000$mcdw$applyDippingPoisonPotionConsumption(class_1309.java:26281) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_6040(class_1309.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.redirect$bbh000$carpet$finishedUsingItem(class_3222.java:6388) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_6040(class_3222.java:1176) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_37119(class_1309.java:3023) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_37119(class_3222.java:1699) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_6076(class_1309.java:3010) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2381) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
	... 10 more
[05:09:51] [Server thread/INFO]: aesthirtruth lost connection: Internal server error
[05:09:51] [Server thread/INFO]: aesthirtruth left the game
`

**Comment by chronosacaria** [comment]
@Aesthir Awesome catch! Thank you, so much! I'll take a look at this today
