### ISSUE TITLE
[Bug Report]: Crashlog submission

### ISSUE THREAD

**Issue by itsdeadfrosty** [chronosacaria/MCDungeonsWeapons#260]
### Describe the bug; What happened?

Crash on launch

### Expected Behavior

runs

### Mod Version

1.20.1

### Minecraft Launcher

Vanilla

### Operating System

Windows

### Modpack

custom

### Additional context

[crash-2024-02-25_15.44.39-client.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/14397791/crash-2024-02-25_15.44.39-client.txt)

**Comment by chronosacaria** [comment]
@itsdeadfrosty You need the Fabric version of Clumps. Also, make sure that you have Connector Extras if you don't already. It is needed for MCDW to work on Forge, at this time.

```
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mcdw'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$0(FabricLoaderImpl.java:131) ~[Connector-1.0.0-beta.36+1.20.1.jar%23683!/:1.0.0-beta.36+1.20.1] {}
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[Connector-1.0.0-beta.36+1.20.1.jar%23683!/:1.0.0-beta.36+1.20.1] {}
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:129) ~[Connector-1.0.0-beta.36+1.20.1.jar%23683!/:1.0.0-beta.36+1.20.1] {}
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.36+1.20.1-mod.jar%23688!/:1.0.0-beta.36+1.20.1] {re:mixin,re:classloading}
	... 18 more
Caused by: java.lang.NoClassDefFoundError: com/blamejared/clumps/api/events/ClumpsEvents
	at chronosacaria.mcdw.registries.CompatRegistry.register(CompatRegistry.java:14) ~[mcdw-9.0.1_mapped_srg_1.20.1.jar%232117!/:?] {re:classloading}
	at chronosacaria.mcdw.Mcdw.onInitialize(Mcdw.java:27) ~[mcdw-9.0.1_mapped_srg_1.20.1.jar%232117!/:?] {re:mixin,re:classloading}
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:127) ~[Connector-1.0.0-beta.36+1.20.1.jar%23683!/:1.0.0-beta.36+1.20.1] {}
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.36+1.20.1-mod.jar%23688!/:1.0.0-beta.36+1.20.1] {re:mixin,re:classloading}
	... 18 more
Caused by: java.lang.ClassNotFoundException: com.blamejared.clumps.api.events.ClumpsEvents
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at chronosacaria.mcdw.registries.CompatRegistry.register(CompatRegistry.java:14) ~[mcdw-9.0.1_mapped_srg_1.20.1.jar%232117!/:?] {re:classloading}
	at chronosacaria.mcdw.Mcdw.onInitialize(Mcdw.java:27) ~[mcdw-9.0.1_mapped_srg_1.20.1.jar%232117!/:?] {re:mixin,re:classloading}
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:127) ~[Connector-1.0.0-beta.36+1.20.1.jar%23683!/:1.0.0-beta.36+1.20.1] {}
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.36+1.20.1-mod.jar%23688!/:1.0.0-beta.36+1.20.1] {re:mixin,re:classloading}
	... 18 more
```

**Comment by itsdeadfrosty** [comment]
Huston we have a problem-

swapped forge for fabric version of clumps, have extras alr, no dice

[crash-2024-02-25_16.48.31-client.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/14397958/crash-2024-02-25_16.48.31-client.txt)

**Comment by gabvichiato** [comment]
getting the same error when it loads up. when switching to fabric cloth config, that error pops up. when not using it, it isn't detected and we still can't play :(

**Comment by chronosacaria** [comment]
@gabvichiato You have not provided a crashlog for your original issue. If you are having the same crash, it is due to something conflicting with Sodium or Rubidium as mentioned in their crashlog here:

```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/client/renderer/LevelRenderer::preventDefaultOffset with priority 1000 cannot inject into net/minecraft/client/renderer/LevelRenderer::m_172993_(Lnet/minecraft/client/renderer/RenderType;Lcom/mojang/blaze3d/vertex/PoseStack;DDDLorg/joml/Matrix4f;)V merged by me.jellysquid.mods.sodium.mixin.core.render.world.WorldRendererMixin with priority 1000 [PREINJECT Applicator Phase -> chunkanimator.mixins.json:LevelRendererMixin from mod (unknown) -> Prepare Injections ->  -> redirect$lcd000$preventDefaultOffset(Lcom/mojang/blaze3d/shaders/Uniform;FFF)V -> Prepare]...
```
