### ISSUE TITLE
[Bug Report]: Game Failed to Initialized on MultiMC MC Java 1.20.1 using Forge 47.3.12 with Connector Mods.

### ISSUE THREAD

**Issue by MrG2kO1GitH** [chronosacaria/MCDungeonsWeapons#306]
### Describe the bug; What happened?

The Game was unable to run on the MultiMC MC Java 1.20.1 on a Asus VivoBook 15 with an OS running latest Win 10 Home 2H22.   I used other mods bundled together along with the:

* Connector Mod by by Sinytra ; https://www.curseforge.com/minecraft/mc-mods/sinytra-connector. 

* Connector Extra by Sinytra ; https://modrinth.com/mod/connector-extras/versions?g=1.20.1&l=forge. 

* Forgified Fabric API Mod ; https://modrinth.com/mod/forgified-fabric-api/versions?g=1.20.1. 

=====Here's the log file:=====

*  [crash-2024-11-08_21.31.43-client.txt](https://github.com/user-attachments/files/17686305/crash-2024-11-08_21.31.43-client.txt)

### Expected Behavior

Because I was running Forge 47.3.12 with a whole bunch of other mods, and the log files specifically highlighted these issues:

Time: 2024-11-08 21:31:43
Description: Initializing game

net.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'main' due to errors, provided by 'mcdw' at 'chronosacaria.mcdw.Mcdw'!
	at org.sinytra.connector.loader.ConnectorEarlyLoader.createLoadingException(ConnectorEarlyLoader.java:81) ~[Connector-1.0.0-beta.46+1.20.1.jar%23174!/:1.0.0-beta.46+1.20.1] {}
	at org.sinytra.connector.loader.ConnectorEarlyLoader.createGenericLoadingException(ConnectorEarlyLoader.java:77) ~[Connector-1.0.0-beta.46+1.20.1.jar%23174!/:1.0.0-beta.46+1.20.1] {}
	at org.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:55) ~[Connector-1.0.0-beta.46+1.20.1-mod.jar%23178!/:1.0.0-beta.46+1.20.1] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.handler$beh000$connectormod$earlyInit(Minecraft.java:19445) ~[client-1.20.1-20230612.114412-srg.jar%23224!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) ~[client-1.20.1-20230612.114412-srg.jar%23224!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:182) ~[minecraft-1.20.1-client.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.emibridge.json:MainEntrypointMixin from mod connectorextras_emi_bridge,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.12.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.12.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.12.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[?:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[?:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[?:?] {}
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mcdw' at 'chronosacaria.mcdw.Mcdw'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$0(FabricLoaderImpl.java:133) ~[Connector-1.0.0-beta.46+1.20.1.jar%23174!/:1.0.0-beta.46+1.20.1] {}
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[Connector-1.0.0-beta.46+1.20.1.jar%23174!/:1.0.0-beta.46+1.20.1] {}
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:131) ~[Connector-1.0.0-beta.46+1.20.1.jar%23174!/:1.0.0-beta.46+1.20.1] {}
	at org.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.46+1.20.1-mod.jar%23178!/:1.0.0-beta.46+1.20.1] {re:mixin,re:classloading}
	... 25 more
	Suppressed: java.lang.NoClassDefFoundError: com/blamejared/clumps/api/events/ClumpsEvents
		at chronosacaria.mcda.registries.CompatRegistry.register(CompatRegistry.java:21) ~[mcda-5.0.2_mapped_srg_1.20.1.jar%23447!/:?] {re:classloading}
		at chronosacaria.mcda.Mcda.onInitialize(Mcda.java:39) ~[mcda-5.0.2_mapped_srg_1.20.1.jar%23447!/:?] {re:mixin,re:classloading}
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:129) ~[Connector-1.0.0-beta.46+1.20.1.jar%23174!/:1.0.0-beta.46+1.20.1] {}
		at org.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.46+1.20.1-mod.jar%23178!/:1.0.0-beta.46+1.20.1] {re:mixin,re:classloading}
		at net.minecraft.client.Minecraft.handler$beh000$connectormod$earlyInit(Minecraft.java:19445) ~[client-1.20.1-20230612.114412-srg.jar%23224!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
		at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) ~[client-1.20.1-20230612.114412-srg.jar%23224!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
		at net.minecraft.client.main.Main.main(Main.java:182) ~[minecraft-1.20.1-client.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.emibridge.json:MainEntrypointMixin from mod connectorextras_emi_bridge,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
		at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
		at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
		at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.12.jar:?] {}
		at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.12.jar:?] {}
		at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.12.jar:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
		at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
		at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
		at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
		at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
		at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
		at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
		at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
		at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
		at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[?:?] {}
		at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[?:?] {}
		at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[?:?] {}
		at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[?:?] {}
	Caused by: java.lang.ClassNotFoundException: com.blamejared.clumps.api.events.ClumpsEvents
		at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?] {}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?] {}
		... 29 more
Caused by: java.lang.NoClassDefFoundError: com/blamejared/clumps/api/events/ClumpsEvents
	at chronosacaria.mcdw.registries.CompatRegistry.register(CompatRegistry.java:20) ~[mcdw-9.0.4_mapped_srg_1.20.1.jar%23450!/:?] {re:classloading}
	at chronosacaria.mcdw.Mcdw.onInitialize(Mcdw.java:35) ~[mcdw-9.0.4_mapped_srg_1.20.1.jar%23450!/:?] {re:mixin,re:classloading}
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:129) ~[Connector-1.0.0-beta.46+1.20.1.jar%23174!/:1.0.0-beta.46+1.20.1] {}
	at org.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.46+1.20.1-mod.jar%23178!/:1.0.0-beta.46+1.20.1] {re:mixin,re:classloading}
	... 25 more
Caused by: java.lang.ClassNotFoundException: com.blamejared.clumps.api.events.ClumpsEvents
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?] {}
	at chronosacaria.mcdw.registries.CompatRegistry.register(CompatRegistry.java:20) ~[mcdw-9.0.4_mapped_srg_1.20.1.jar%23450!/:?] {re:classloading}
	at chronosacaria.mcdw.Mcdw.onInitialize(Mcdw.java:35) ~[mcdw-9.0.4_mapped_srg_1.20.1.jar%23450!/:?] {re:mixin,re:classloading}
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:129) ~[Connector-1.0.0-beta.46+1.20.1.jar%23174!/:1.0.0-beta.46+1.20.1] {}
	at org.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.46+1.20.1-mod.jar%23178!/:1.0.0-beta.46+1.20.1] {re:mixin,re:classloading}
	... 25 more
I hope this wouldn't be of any trouble.

### Mod Version

9.0.4 Forge

### Minecraft Launcher

MultiMC

### Operating System

Windows

### Modpack

No Mod Packs, it was individually and Separately Downloaded.

### Additional context

Connector Mod and Connector Extra Mod by Sinyatra & Forgified Fabric API Mod by Su5eD. Forge Mod Launcher on a Asus VivoBook 15 AMD running on Windows 10 Home 2H22.

**Comment by chronosacaria** [comment]
@MrG2kO1GitH You're using the wrong version of Clumps. Change to the version of Clumps that is for Fabric and that will resolve your issue

**Comment by MrG2kO1GitH** [comment]
Ok
