### ISSUE TITLE
[Bug Report]: 1.20.1 Forge crashed at launch

### ISSUE THREAD

**Issue by Orangeboi69** [chronosacaria/MCDungeonsWeapons#307]
### Describe the bug; What happened?

1. Install the mod with all of it's required dependencies(with the mod from my mod pack)
2. Launch the game
3. Crashes after a few second

[Client Log](https://mclo.gs/s7s8Zm5)
[Crash Log?](https://mclo.gs/nM04ftj)

Part of the client log(?):
```
[1611月2024 14:40:31.656] [pool-4-thread-1/WARN] [mixin/]: @Final field delegatesByName:Ljava/util/Map; in modernfix-forge.mixins.json:perf.forge_registry_alloc.ForgeRegistryMixin from mod modernfix should be final
[1611月2024 14:40:31.656] [pool-4-thread-1/WARN] [mixin/]: @Final field delegatesByValue:Ljava/util/Map; in modernfix-forge.mixins.json:perf.forge_registry_alloc.ForgeRegistryMixin from mod modernfix should be final
[1611月2024 14:40:31.820] [pool-4-thread-1/INFO] [ModernFix/]: Injecting BlockStateBase cache population hook into getNeighborPathNodeType from com.abdelaziz.canary.mixin.ai.pathing.BlockStateBaseMixin
[1611月2024 14:40:31.820] [pool-4-thread-1/INFO] [ModernFix/]: Injecting BlockStateBase cache population hook into getPathNodeType from com.abdelaziz.canary.mixin.ai.pathing.BlockStateBaseMixin
[1611月2024 14:40:32.636] [pool-4-thread-1/INFO] [mixin/]: Instancing error handler class org.valkyrienskies.mod.mixin.ValkyrienMixinErrorHandler
[1611月2024 14:40:32.636] [pool-4-thread-1/INFO] [mixin/]: Instancing error handler class com.illusivesoulworks.polymorph.mixin.IntegratedMixinPlugin
[1611月2024 14:40:32.637] [pool-4-thread-1/FATAL] [mixin/]: Mixin apply for mod mcdw failed mcdw.mixins.json:reach.PlayerEntityMixin from mod mcdw -> net.minecraft.world.entity.player.Player: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Implicit variable modifier injection failed in net/minecraft/world/entity/player/Player::mcdw$modifyAttackRange [INJECT Applicator Phase -> mcdw.mixins.json:reach.PlayerEntityMixin from mod mcdw -> Apply Injections -> -> Inject -> mcdw.mixins.json:reach.PlayerEntityMixin from mod mcdw->@ModifyVariable::mcdw$modifyAttackRange(D)D]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Implicit variable modifier injection failed in net/minecraft/world/entity/player/Player::mcdw$modifyAttackRange [INJECT Applicator Phase -> mcdw.mixins.json:reach.PlayerEntityMixin from mod mcdw -> Apply Injections -> -> Inject -> mcdw.mixins.json:reach.PlayerEntityMixin from mod mcdw->@ModifyVariable::mcdw$modifyAttackRange(D)D]
at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:216) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30]
at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?]
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?]
at net.minecraftforge.registries.GameData.init(GameData.java:107) ~[forge-1.20.1-47.3.12-universal.jar%23713!/:?]
at net.minecraftforge.registries.GameData.<clinit>(GameData.java:93) ~[forge-1.20.1-47.3.12-universal.jar%23713!/:?]
at net.minecraft.core.registries.BuiltInRegistries.forge(BuiltInRegistries.java:429) ~[client-1.20.1-20230612.114412-srg.jar%23708!/:?]
at net.minecraft.core.registries.BuiltInRegistries.forge(BuiltInRegistries.java:409) ~[client-1.20.1-20230612.114412-srg.jar%23708!/:?]
at net.minecraft.core.registries.BuiltInRegistries.<clinit>(BuiltInRegistries.java:121) ~[client-1.20.1-20230612.114412-srg.jar%23708!/:?]
at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43) ~[client-1.20.1-20230612.114412-srg.jar%23708!/:?]
at net.minecraft.client.main.Main.lambda$main$0(Main.java:151) ~[client-1.20.1-20230612.114412-srg.jar%23708!/:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
at java.lang.Thread.run(Thread.java:1575) ~[?:?]
Caused by: org.spongepowered.asm.mixin.injection.modify.InvalidImplicitDiscriminatorException: Found 2 candidate variables but exactly 1 is required.
at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator.findImplicitLocal(LocalVariableDiscriminator.java:370) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator.findLocal(LocalVariableDiscriminator.java:341) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:207) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
... 34 more
```

### Expected Behavior

Launch normally

### Mod Version

9.0.4

### Minecraft Launcher

Other

### Operating System

Windows

### Modpack

Private, Modlist: https://pastebin.com/TdyeNKNa

### Additional context

When I remove MCDW, minecraft will launch normally.
Launcher: Modrinth App
I have tried:

- [x] Removing Embeddium Extra
- [x] Removing Oculus
- [x] Removing Clumps
- [x] Removing Memory Leak fix

> Crashed at loading bootstrap resources(says the loading screen)

**Comment by chronosacaria** [comment]
As stated on the MCDW mod page: 

When using MCDX on Forge, it is important to make sure that you have the following mods:
So, anything marked with a 🟢 is required. Anything marked with a 🟡 is optional

🟢Sinytra Connector:
https://www.curseforge.com/minecraft/mc-mods/sinytra-connector/

🟢Connector Extras:
https://www.curseforge.com/minecraft/mc-mods/connector-extras/
🟢Forgified Fabric API (in place of the Fabric API):
https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api/

🟢Cloth Config API (Forge Version*):
https://www.curseforge.com/minecraft/mc-mods/cloth-config/
If you are using a version of the Sinytra Connector before 40, use the Fabric version

🟡Clumps (Fabric Version), if you're using Clumps:
https://www.curseforge.com/minecraft/mc-mods/clumps/

Please use the respective links for your preferred modloader. The note I have access to on mobile just happens to be the CurseForge version. 

When looking at your log, it appears you are, at minimum, missing the Connector Extras mod and may be using the wrong version of Clumps. Should you need this information in another language, please let me know what language you need and I can provide that information to you

**Comment by chronosacaria** [comment]
I realised that I forgot to ping you. @Orangeboi69, please see the above message for a solution to your issue

**Comment by Orangeboi69** [comment]
Upon further testing, I found out that the problem probably isn't by MCDW.
I have:
- [x] Sinytra Connector(1.0.0-beta.46+1.20.1)
- [x] Connector Extras(1.11.2+1.20.1)
- [x] Forgified Fabric API(0.92.2+1.11.8+1.20.1)
- [x] Cloth Config ApI(11.1.136+forge)
- [ ] MCDW (9.0.4)
Without MCDW and when I try to start it, it crashes. Seems like a problem by Connector Extras and Sinytra Connector. Sorry for bothering.
