### ISSUE TITLE
STDERR Exception when downloading translations

### ISSUE THREAD

**Issue by Greg-J** [chronosacaria/MCDungeonsWeapons#48]
I _think_ this is due to one of the MCD mods based on the error, but I'm not sure.

```
[11:22:10] [Thread-235/INFO]: [STDERR]: Exception when downloading translations
[11:22:10] [Thread-235/INFO]: [STDERR]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2661)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2583)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1769)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at java.net.URL.openStream(URL.java:1038)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at de.guntram.mcmod.crowdintranslate.CrowdinTranslate.getCrowdinTranslations(CrowdinTranslate.java:155)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at de.guntram.mcmod.crowdintranslate.CrowdinTranslate.run(CrowdinTranslate.java:124)
[11:22:10] [Thread-235/INFO]: [STDERR]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.validator.Validator.validate(Validator.java:260)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	... 17 more
[11:22:10] [Thread-235/INFO]: [STDERR]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
[11:22:10] [Thread-235/INFO]: [STDERR]: 	... 23 more
```

**Comment by chronosacaria** [comment]
Based on what, exactly? I am not seeing anything that specifically points towards one of my mods. Do you have more information that this? A crash log or something along those lines would be really helpful

**Comment by Greg-J** [comment]
That's why I said _I think_. I'm only basing this on the `de.guntram.mcmod.crowdintranslate` reference. I thought mcmod could reference your mods since you use the mc*mod format, but now I realize it could easily just be a generic reference to MineCraft mod.
