### ISSUE TITLE
[1.17.1][v3.4.1] Crash when attempting to scroll down creative tab

### ISSUE THREAD

**Issue by abdmoh123** [chronosacaria/MCDungeonsWeapons#55]
Seems there is a class casting error caused when loading up a spear (see log below).
I had the Iris shaders mod installed (includes sodium) could that be causing the problem? or is it a bug in this mod.

Log file:
[00:00:33] [Render thread/FATAL]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:883) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1112) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: java.lang.ClassCastException: class chronosacaria.mcdw.bases.McdwSpear cannot be cast to class net.minecraft.class_1766 (chronosacaria.mcdw.bases.McdwSpear and net.minecraft.class_1766 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @5e21e98f)
	at net.minecraft.class_1799.handler$dgb000$getTooltipMixin(class_1799.java:7338) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1799.method_7950(class_1799.java:677) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_437.method_25408(class_437.java:181) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_437.method_25409(class_437.java:168) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_481.method_25409(class_481.java:742) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_465.method_2380(class_465.java:190) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_481.method_25394(class_481.java:703) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:874) ~[intermediary-1.17.1.jar:?]
	... 10 more

**Comment by chronosacaria** [comment]
Please send me the whole crash log, not just part of it. Having only part of it doesn't actually help me

**Comment by abdmoh123** [comment]
ok sorry I will send both the crash report now.

Crash report:
https://pastebin.com/7xMdinMB

**Comment by chronosacaria** [comment]
Awesome! Thanks, so much!

**Comment by chronosacaria** [comment]
Well, I can confirm that it is not a bug with the mod. I tested it with just the mod installed and I did not get the crash. I am going to test with Iris now

**Comment by chronosacaria** [comment]
The issue also, does not appear to be caused, specifically, by Iris, either as both mods can be installed without causing an issue. Something is trying to force the spears to be classified as a `MiningToolItem` when they are actually `McdwCustomWeaponBase` which are both extensions of `ToolItem`. I am not sure what is causing this issue, but it does not appear to be my mod, though it would appear that my mod is being affected by something else. I'll try to figure this one out.

Thanks for bringing it to my attention, even if it looks like there really isn't anything that I can do to help with this one at this time

**Comment by abdmoh123** [comment]
Yeah the problem must be with another mod. Thanks for helping though

**Comment by chronosacaria** [comment]
Actually, I see that you are using Dashloader, I think that it _could_ be what is causing the issue. It tends to skip a lot of initialisation steps

**Comment by abdmoh123** [comment]
I just tested it without dashloader. The problem no longer exists ahaha.
