### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by C10udburst** [chronosacaria/MCDungeonsWeapons#76]
I have disabled all the crossbows in the config file, the rest of the config is default.

```
---- Minecraft Crash Report ----
// My bad.

Time: 06.01.2022, 13:06
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "chronosacaria.mcdw.bases.McdwCrossbow.method_8389()" because the return value of "java.util.EnumMap.get(Object)" is null
	at net.minecraft.class_1764.handler$boh000$createBonusShotArrow(class_1764.java:537)
	at net.minecraft.class_1764.method_18814(class_1764.java:262)
	at net.minecraft.class_1764.method_7763(class_1764.java:225)
	at net.minecraft.class_1764.method_7777(class_1764.java:278)
	at net.minecraft.class_3745.method_24654(class_3745.java:32)
	at net.minecraft.class_1604.method_7105(class_1604.java:233)
	at net.minecraft.class_1383.method_6268(class_1383.java:143)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:119)
	at net.minecraft.class_1355.method_6275(class_1355.java:110)
	at net.minecraft.class_1308.method_6023(class_1308.java:741)
	at net.minecraft.class_1309.method_6007(class_1309.java:2604)
	at net.minecraft.class_1308.method_6007(class_1308.java:545)
	at net.minecraft.class_1588.method_6007(class_1588.java:43)
	at net.minecraft.class_3763.method_6007(class_3763.java:114)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.minecraft.class_1308.method_5773(class_1308.java:345)
	at net.minecraft.class_3218.redirect$cmd000$shouldTickEntity(class_3218.java:10168)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.redirect$zkb000$fixUpdateSuppressionCrashTick(MinecraftServer.java:4754)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.handler$zdb000$modifiedRunLoop(MinecraftServer.java:3856)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1764.handler$boh000$createBonusShotArrow(class_1764.java:537)
	at net.minecraft.class_1764.method_18814(class_1764.java:262)
	at net.minecraft.class_1764.method_7763(class_1764.java:225)
	at net.minecraft.class_1764.method_7777(class_1764.java:278)
	at net.minecraft.class_3745.method_24654(class_3745.java:32)
	at net.minecraft.class_1604.method_7105(class_1604.java:233)
	at net.minecraft.class_1383.method_6268(class_1383.java:143)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:119)
	at net.minecraft.class_1355.method_6275(class_1355.java:110)
	at net.minecraft.class_1308.method_6023(class_1308.java:741)
	at net.minecraft.class_1309.method_6007(class_1309.java:2604)
	at net.minecraft.class_1308.method_6007(class_1308.java:545)
	at net.minecraft.class_1588.method_6007(class_1588.java:43)
	at net.minecraft.class_3763.method_6007(class_3763.java:114)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.minecraft.class_1308.method_5773(class_1308.java:345)
	at net.minecraft.class_3218.redirect$cmd000$shouldTickEntity(class_3218.java:10168)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.redirect$zkb000$fixUpdateSuppressionCrashTick(MinecraftServer.java:4754)

-- Entity being ticked --
Details:
	Entity Type: minecraft:pillager (net.minecraft.class_1604)
	Entity ID: 4290
	Entity Name: Pillager
	Entity's Exact location: -2852.30, 72.00, -1234.58
	Entity's Block location: World: (-2853,72,-1235), Section: (at 11,8,13 in -179,4,-78; chunk contains blocks -2864,-64,-1248 to -2849,319,-1233), Region: (-6,-3; contains chunks -192,-96 to -161,-65, blocks -3072,-64,-1536 to -2561,319,-1025)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.redirect$zkb000$fixUpdateSuppressionCrashTick(MinecraftServer.java:4754)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.handler$zdb000$modifiedRunLoop(MinecraftServer.java:3856)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Cl0udburst'/492, l='ServerLevel[world]', x=-2863.71, y=69.17, z=-1233.69]]
	Chunk stats: 2401
	Level dimension: minecraft:overworld
	Level spawn location: World: (-272,67,-80), Section: (at 0,3,0 in -17,4,-5; chunk contains blocks -272,-64,-80 to -257,319,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 48208 game time, 39067 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 6860 (now: false), thunder time: 40767 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.handler$zdb000$modifiedRunLoop(MinecraftServer.java:3856)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 622173944 bytes (593 MiB) / 1459617792 bytes (1392 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3800X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3,89
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 5700 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x731f
	Graphics card #0 versionInfo: DriverVersion=27.20.22021.1002
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 3,20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 3,20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 25511,04
	Virtual memory used (MB): 19292,92
	Swap memory total (MB): 9216,00
	Swap memory used (MB): 370,15
	JVM Flags: 1 total; -Xmx2G
	Fabric Mods: 
		adapaxels: AdaPaxels 1.3.1+1.18-rc3
		adventure-platform-fabric: adventure-platform-fabric 5.0.0
		alternatecurrent: Alternate Current 1.1.0
		amplified_nether: Amplified Nether for Fabric 1.0.1
		anvilrestoration-fabric: Anvil Restoration (Fabric) 1.1
		aqupdhat: Hat command 1.18-2.3.1
		autoconfig1u: Auto Config v1 Updated 3.3.1
		awesomedungeon: Awesome Dungeon 2.0.2
		axesareweapons: Axes Are Weapons 1.5.1
		bakingmod: Baking Mod 1.18.1
		beehive: Beehive 1.0.0
		bfapi: BFAPI 1.2.1
		book_of_the_day: Book of the Day 1.1.0
		bottledair-fabric: Bottled Air (Fabric) 1.0
		bottleyourxp-fabric: Bottle Your Xp (Fabric) 1.6
		cardinal-components-base: Cardinal Components API (base) 4.0.0
		cardinal-components-entity: Cardinal Components API (entities) 4.0.0
		carpet: Carpet Mod 1.4.56
		carpet-extra: Carpet Extra 1.4.56
		castle_dungeons: Castle Dungeons 3.1-1.18-fabric
		clientbrand: Client Brand 1.0.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		cloud: Cloud 1.6.0
		cloud_commandframework_cloud-brigadier_: cloud-brigadier 1.6.0
		cloud_commandframework_cloud-core_: cloud-core 1.6.0
		cloud_commandframework_cloud-minecraft-extras: cloud-minecraft-extras 1.6.0
		cloud_commandframework_cloud-services_: cloud-services 1.6.0
		collective-fabric: Collective (Fabric) 3.14
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		compacthelpcommand-fabric: Compact Help Command (Fabric) 1.1
		confabricate: confabricate 2.1.0-SNAPSHOT+4.1.1
		config2brigadier: Config to Brigadier 1.0.2
		denseores: Dense Ores: Refabricated 1.2.1+1.18.1
		dungeons_arise: When Dungeons Arise 2.1.49b-fabric
		dungeonvanilla: Dungeon vanilla 2.0.2
		edibles-fabric: Edibles (Fabric) 2.4
		em4es: EM4ES: ExplorerMapForEveryStructure 1.0.1
		enchant_giver: Enchant Giver 1.1.0
		enhancedcelestials: Enhanced Celestials 2.0.6
		essentialsnt: Essentialsn't 1.0.3
		extrasponges: ExtraSponges 1.2.0
		fabric: Fabric API 0.45.2+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.9+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.8+b4f4f6cd65
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.9+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.0+befed49e65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.5+fb3b57b465
		fabric-tpa: FabricTPA 3.1.0
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabrichomes: FabricHomes 2.2.0
		fabricloader: Fabric Loader 0.12.12
		fabricsit: FabricSit 1.7.1
		fabrictailor: Fabric Tailor 1.7.3
		fabrilousupdater: FabrilousUpdater 2.5+1.18.1
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric $version
		ferritecore: FerriteCore 4.0.0
		fiber: fiber 0.23.0-2
		glow_potion: Glow Potion 1.0-SNAPSHOT
		harvest_scythes: Harvest Scythes 2.4.0
		healthcare: Health Care 1.0.10
		hologram-api: Hologram API 0.2.1+1.18-pre5
		icyincitement: Icy Incitement 1.18.1-fabric-1.0.0
		image2map: Image2Map 0.2.2
		imperishableitems: Imperishable Items 2.1.1
		incantationem: Incantationem 1.1.3+1.18.1
		inmis: Inmis 2.4.0-1.18
		io_leangen_geantyref_geantyref: geantyref 1.3.13
		java: OpenJDK 64-Bit Server VM 17
		just_end_anchor: Just An End Anchor 1.0.1
		krypton: Krypton 0.1.6
		lazydfu: LazyDFU 0.1.2
		libcd: LibCapableData 3.0.3+1.16.3
		libraryferret: Library Ferret 1.0.2
		lithium: Lithium 0.7.7
		luckperms: LuckPerms 5.3.87
		magna: Magna 1.7.0-1.18-pre1
		maybe-data: Maybe data 1.0.1-1.17
		mcdar: MC Dungeons Artifacts 1.4.3-1.18
		mcdw: MC Dungeons Weapons 4.0.1
		mighty_mangoes: Mighty Mangoes 1.0.6
		milkallthemobs-fabric: Milk All The Mobs (Fabric) 1.6
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		mob_catcher: Mob Catcher 1.1.20
		mobspecificenchants: MobSpecificEnchants 1.1.0
		mods-command: Mods Command 1.0.5
		morevillagers: MoreVillagersFabric 3.1.0-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1+1.18
		nbtcrafting: NBT Crafting 2.1.0+mc1.18-pre1
		nears: Nears 1.1.2
		net_kyori_adventure-api: adventure-api 4.9.3
		net_kyori_adventure-key: adventure-key 4.9.3
		net_kyori_adventure-platform-api: adventure-platform-api 4.0.0
		net_kyori_adventure-serializer-configurate4: adventure-serializer-configurate4 4.9.3
		net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
		net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.2.0-SNAPSHOT
		net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.9.3
		net_kyori_adventure-text-serializer-legacy: adventure-text-serializer-legacy 4.9.3
		net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.9.3
		net_kyori_examination-api: examination-api 1.3.0
		net_kyori_examination-string: examination-string 1.3.0
		nmtp: No More Tree Punching Alpha-1.0
		no_null_processors: No Null Processors - Fabric 2.0.1+1.18.1
		noenchantcap: No Enchant Cap 1.18.1-fabric-2.1.1
		omega-config: OmegaConfig 1.1.0
		onastick: On A Stick 2.0.0
		org_spongepowered_configurate-core: configurate-core 4.1.2
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		org_spongepowered_configurate-yaml: configurate-yaml 4.1.2
		org_yaml_snakeyaml: snakeyaml 1.30
		packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		perfectaccuracy: Perfect Accuracy 1.2
		placeholder-api: Placeholder API 1.1.3+1.17.1
		polymc: PolyMc 3.3.3+1.18.1
		polymer: Polymer 0.2.0-beta.15+1.18.1
		polymer-legacy: Polymer (Compatibility) 0.1.9+0.2.0-beta.15+1.18.1
		quartzelv: Quartz Elevator 2.0.1+1.18
		randomshulkercolours-fabric: Random Shulker Colours (Fabric) 1.3
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		recipecache: recipecache 0.2.1-1.17.1
		renameit: RenameIt 1.0.1
		repurposed_structures: Repurposed Structures 3.2.0+1.18.1
		ring_of_growth: Ring Of Growth 1.2.18
		seedfix: Seed Fix 1.0.0
		server_translations_api: Server Translations API 1.4.8+1.18-pre1
		servercore-fabric: ServerCore-Fabric 1.2.6-1.18.1
		sgui: sgui 1.0.0-rc6+1.18-pre5
		skyvillages: Sky Villages 1.0.1-1.18.1-fabric
		spiceoffabric: Spice of Fabric 1.4.1+1.18-pre5
		starlight: Starlight 1.0.0+fabric.d0a3220
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		stoneholm: Stoneholm 1.4
		styledchat: Styled Chat 1.2.3+1.18
		suitablystackablestew: Suitably Stackable Stew 1.1.2
		sulfurpotassiummod: Sulfur & Potassium 1.1.1
		tabtps-fabric: TabTPS 1.3.11
		terralith: Terralith for Fabric 2.0.8
		torchbowmod: TorchBowMod 1.0
		totw_additions: Towers of the Wild: Additions 1.1.0
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 2.1.0
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		universal-graves: Universal Graves 2.0.0-beta.3+1.18
		vanilla-hammers: Vanilla Hammers 3.2.0-1.18.1
		viabackwards: ViaBackwards 4.1.1
		viafabric: ViaFabric 0.4.5+253-main
		viafabric-mc118: ViaFabric for 1.18 0.4.5+253-main
		viarewind: ViaRewind 2.0.2
		viaversion: ViaVersion 4.1.2-SNAPSHOT
		voidtotem: VoidTotem (Fabric) 1.18.1-1.1.0
		wthit: wthit 4.4.1
		zombify: Zombify 0.1.0
	Server Running: true
	Player Count: 1 / 35; [class_3222['Cl0udburst'/492, l='ServerLevel[world]', x=-2863.71, y=69.17, z=-1233.69]]
	Data Packs: vanilla, Fabric Mods, file/CraftingTweaks.zip, file/PlatyPack+1.7.0.1.zip (incompatible), file/desert-village-1-18.zip, file/double shulker shells v1.3.2.zip, file/gen1-salvaging.zip (incompatible), file/more mob heads v2.9.4.zip, file/pertified_oak_slab.zip, file/player head drops v1.1.2.zip, file/woodfellas-e1600.zip (incompatible)
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by chronosacaria** [comment]
Thanks! I'll be taking a look at this
