### ISSUE TITLE
Glaive crashing aternos server

### ISSUE THREAD

**Issue by SpaghettiCoder4951** [chronosacaria/MCDungeonsWeapons#99]
What the bug is doing is after having the latest version of Mc dungeons weapons for 1.18.1 my friend looked in the sky hit with the glaive in the sky then hit the ground and crashed the entire server but when I did it nothing was wrong

1. Get a glaive
2. Look up at the sky and attack
3. Look down at the floor and attack
4. Crashes entire server

**Please complete the following information:**
 - I am on a windows 11 pc my friend who did it was on a Mac my other friend who also crashed the server was also on windows 11
 - Normal Mc launcher
 - 4.2.2
 - I am not using a modpack I do have multiple mods on the server though

**Comment by chronosacaria** [comment]
Could you provide the crash report please? Without it I can't actually tell what is wrong. I will try to reproduce the issue tomorrow, however, either way

**Comment by SpaghettiCoder4951** [comment]
There is no crash report, it crashes the entire server that is it I will send all the mods used in the server though

**Comment by SpaghettiCoder4951** [comment]
![image](https://user-images.githubusercontent.com/100983825/156888540-955af955-7b61-4abe-8e6b-d184170670b5.png)

**Comment by SpaghettiCoder4951** [comment]
![image](https://user-images.githubusercontent.com/100983825/156888554-f3b9ede9-341c-4270-b563-a740148977a8.png)

**Comment by SpaghettiCoder4951** [comment]
Also let me add, that my friend was able to hit mobs no problem but I think its when hitting a block is what is causing the issue

**Comment by N0obitty** [comment]
Umm hello, got the same issue with the following error in the aternos logs



[23:43:37] [Server thread/ERROR]: Encountered an unexpected exception
--
401 | java.lang.NoSuchFieldError: field_15503
402 | at chronosacaria.mcdw.bases.McdwGlaive.method_7865(McdwGlaive.java:90) ~[mcdw-4.2.2.jar:?]
403 | at net.minecraft.class_1799.method_7924(class_1799.java:248) ~[server-intermediary.jar:?]
404 | at net.minecraft.class_1661.method_7370(class_1661.java:420) ~[server-intermediary.jar:?]
405 | at net.minecraft.class_1657.method_7351(class_1657.java:754) ~[server-intermediary.jar:?]
406 | at net.minecraft.class_4970.method_9594(class_4970.java:377) ~[server-intermediary.jar:?]
407 | at net.minecraft.class_4970$class_4971.method_26165(class_4970.java:793) ~[server-intermediary.jar:?]
408 | at net.minecraft.class_3225.method_14263(class_3225.java:168) ~[server-intermediary.jar:?]
409 | at net.minecraft.class_3244.method_12066(class_3244.java:1019) ~[server-intermediary.jar:?]
410 | at net.minecraft.class_2846.method_12361(class_2846.java:34) ~[server-intermediary.jar:?]
411 | at net.minecraft.class_2846.method_11054(class_2846.java:8) ~[server-intermediary.jar:?]
412 | at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[server-intermediary.jar:?]
413 | at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
414 | at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[server-intermediary.jar:?]
415 | at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
416 | at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780) ~[server-intermediary.jar:?]
417 | at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162) ~[server-intermediary.jar:?]
418 | at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[server-intermediary.jar:?]
419 | at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762) ~[server-intermediary.jar:?]
420 | at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756) ~[server-intermediary.jar:?]
421 | at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[server-intermediary.jar:?]
422 | at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740) ~[server-intermediary.jar:?]
423 | at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688) ~[server-intermediary.jar:?]
424 | at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
425 | at java.lang.Thread.run(Thread.java:833) [?:?]


</body>
</html>[23:43:37] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchFieldError: field_15503
	at chronosacaria.mcdw.bases.McdwGlaive.method_7865(McdwGlaive.java:90) ~[mcdw-4.2.2.jar:?]
	at net.minecraft.class_1799.method_7924(class_1799.java:248) ~[server-intermediary.jar:?]
	at net.minecraft.class_1661.method_7370(class_1661.java:420) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_7351(class_1657.java:754) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970.method_9594(class_4970.java:377) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26165(class_4970.java:793) ~[server-intermediary.jar:?]
	at net.minecraft.class_3225.method_14263(class_3225.java:168) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12066(class_3244.java:1019) ~[server-intermediary.jar:?]
	at net.minecraft.class_2846.method_12361(class_2846.java:34) ~[server-intermediary.jar:?]
	at net.minecraft.class_2846.method_11054(class_2846.java:8) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[server-intermediary.jar:?]
	at net.minecraft.class_[409](https://mclo.gs/FSvhj6f#L409)3.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20[415](https://mclo.gs/FSvhj6f#L415)(MinecraftServer.java:762) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Kluzzio** [comment]
Will take effect next release, until then, avoid hitting grass with whips, glaives, staves, and spears as those all cause crash unless you update to 1.18.2.
